### ISSUE TITLE
Unable to convert function return value to a python type the signature was () -> handle

### ISSUE THREAD

**Issue by tonybeijes** [ezloj/TQModdingAdvanced#67]
I am using deepface in a python script and would like to package it as a single executable file. For this I am using pyinstaller, however it is giving me this error when I try to run the executable after it has been created. I am using python 3.11.

This is the command I am using - pyinstaller --noconfirm --onefile --windowed "C:/faceRec/FaceRecognition_FIND.py"

And this is the error from the executable:

Unable to convert function return value to a python type the signature was () -> handle

Traceback (most recent call last):
  File "FaceRecognition_FIND.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "deepface\DeepFace.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\__init__.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\saved_model.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\builder.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
 File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\saved_model\builder_impl.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "tensorflow\python\framework\dtypes.py", line 37, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
    () -> handle
I have tried changing my tensorflow and numpy packages but with no changes in results. I have also tried using the add data argument with a 'hook-tensorflow.py' script (seen below) but that did not help either

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

binaries = collect_submodules('tensorflow')
datas = collect_data_files('tensorflow')

hiddenimports = ['tensorflow._api.v2.compat.v1.experimental']  # Adjust as needed

**Comment by ezloj** [comment]
Hi there @tonybeijes!

I don't think you got the right project for this issue.
I think you'll have better luck at https://github.com/pyinstaller/pyinstaller

This particular project is for a GUI tool called TQMA and it only uses pyinstaller.
I am no expert or developer of pyinstaller so I'm not going to be of much help with this.
